version: 2

# Set the version of Python
build:
  os: ubuntu-20.04  # <- add this line
  tools:
    python: "3.9"

# Configuration for Sphinx documentation
sphinx:
   configuration: docs/conf.py
   fail_on_warning: true


python:
  install:
    - requirements: docs/requirements.txt
      method: pip

  
  
  
#   setup_py_install: true
#    system_packages: true
